### ISSUE TITLE
Zabbix 3.0 is released

### ISSUE THREAD

**Issue by dj-wasabi** [dj-wasabi/ansible-zabbix-server#12]
Zabbix 3.0 is released.

**Comment by ericsysmin** [comment]
i am down to help as I am actively deploying this in our environment in a new test, i used to run a zabbix module for puppet but since then, you've done a lot of improvements figured helping with yours may be better

**Comment by lhoss** [comment]
is there a date estimate to get Zabbix 3.0 (upgrade) deployment support ?

**Comment by dj-wasabi** [comment]
I try to release it this week.  I'll update this ticket when Zabbix 3.0 is supported.

**Comment by dj-wasabi** [comment]
@lhoss 
I just release 0.5.0 to the Galaxy.
