### ISSUE TITLE
Support for v3+ Server Configuration

### ISSUE THREAD

**Issue by MVKozlov** [dj-wasabi/ansible-zabbix-server#13]
(bug: v2 only, must be v2+v3)
StartTimers={{ server_starttimers }} 
StartVMwareCollectors={{ server_startvmwarecollectors }}
ValueCacheSize={{ server_valuecachesize }}
AllowRoot={{ server_allowroot }}
LoadModulePath={{ server_loadmodulepath }}

v3+ (or may be earlier, but not supported now)
StartEscalators={{ server_startescalators }}
VMwarePerfFrequency={{ server_vmwareperffrequency }}
VMwareTimeout={{ server_vmwaretimeout }}
HistoryIndexCacheSize={{ server_historyindexcachesize }}
User={{ server_user }}

ssl:
SSLCertLocation=${datadir}/zabbix/ssl/certs
SSLKeyLocation=${datadir}/zabbix/ssl/keys
SSLCALocation=

btw, mysql_db module support import from sql.gz - unpacking not needed
I solve it this way:
- name: "MySQL | Create database"
  mysql_db: name={{ server_dbname }}
            state=present
  when: zabbix_database_creation
  tags:
    - zabbix-server
    - database
  register: zabbix_database_created

- name: "MySQL | Importing data file v3+"
  mysql_db:
    state: import
    name: "{{ server_dbname }}"
    target: "{{ datafiles_path }}/create.sql.gz"
    login_host: "{{ server_dbhost }}"
    login_user: "{{ server_dbuser }}"
    login_password: "{{ server_dbpassword }}"
  when: zabbix_database_sqlload and zabbix_version >= 3 and zabbix_database_created.changed == true
  tags:
    - zabbix-server
    - database

**Comment by dj-wasabi** [comment]
HI @MVKozlov 

I just pushed release 0.5.1 for the missing configuration options.
Will take a look at the MySQL part for 0.6.0.

Thanks!

**Comment by dj-wasabi** [comment]
Just pushed 0.6.0 to the galaxy.
