### ISSUE TITLE
Failed to set permissions on the temporary files

### ISSUE THREAD

**Issue by fernandolcx** [dj-wasabi/ansible-zabbix-server#138]
**Describe the bug**

This has been reported on #29 but it's happening everytime with me.

The following message is thrown when running the Create Database task:

```
TASK [dj-wasabi.zabbix-server : PostgreSQL | Delegated | Create database] ********************************************************************************

fatal: [192.168.170.134]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1549076605.5-17742358543893/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1549076605.5-17742358543893/AnsiballZ_postgresql_db.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

**Installation method/version**

* Ansible Galaxy / 1.3

**Ansible Version**

```
2.7.6
```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu 18.04
* Debian 9.5

**Expected behavior**

**Additional context**

**Comment by dj-wasabi** [comment]
Hi @fernandolcx 

It seems that it is an Ansible related issue, see the link in the error. It basically mentions that you can set the property `allow_world_readable_tmpfiles=True` in the `ansible.cfg` file.

As this is an Ansible issue, I'll close this issue as I can't do anything about it.
