### ISSUE TITLE
apache 2.2. and 2.4

### ISSUE THREAD

**Issue by goern** [dj-wasabi/ansible-zabbix-server#15]
Looks like access control has changes from apache 2.2 to 2.4, http://httpd.apache.org/docs/2.4/upgrading.html#access at least on CentOS7 the configuration deployed by zabbix-server role uses the old keywords.

**Comment by dj-wasabi** [comment]
I pushed an fix for this. It will determine which version of Apache is installed and use the correct vhost syntax. Please let me know if you have any issues.

**Comment by dj-wasabi** [comment]
Just pushed 0.6.0 to the galaxy.
