### ISSUE TITLE
Zabbix default password

### ISSUE THREAD

**Issue by jefersonlemos** [dj-wasabi/ansible-zabbix-server#152]
**Describe the bug**
Unable to find in code the default frontend password. It could be easier if the default username and password were documented in the Readme.md. 

**Expected behavior**
- Maybe the default password configured during code execution could be documented right in the repo.
- Would be possible to set it up as a varible during Ansible execution.

**Comment by dj-wasabi** [comment]
Hi @jefersonlemos 

Default Username/password is now documented in the readme.
