### ISSUE TITLE
Is installation over Tunnel-SSH possible?

### ISSUE THREAD

**Issue by Burnfaker** [dj-wasabi/ansible-zabbix-server#16]
Hello,

we have to much Firewall-Rules and its not possible to open any ports to any zabbix-Server/Proxy/Agent. It is possible to tunnel youre playbook over SSH Tunnel automaticaly?

**Comment by dj-wasabi** [comment]
I don't know? You can configure the server, agent, proxy to run it on an other port. But this can be confusing.
