### ISSUE TITLE
`version_compare` is not available in ansible `2.9.0`

### ISSUE THREAD

**Issue by gregolsky** [dj-wasabi/ansible-zabbix-server#163]
**Describe the bug**
`version_compare` is not available in ansible `2.9.0`. It was renamed to `version` in Ansible `2.5`.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#id8

```
TASK [dj-wasabi.zabbix-server : Set some variables] ******************************************************************************************************************************************************
fatal: [cloudmon-test]: FAILED! => {"msg": "template error while templating string: no filter named 'version_compare'. String: python{% if ansible_python_version | version_compare('3', '>=') %}3{% endif %}"}
```

**Installation method/version**
`ansible-galaxy install dj-wasabi.zabbix-server dj-wasabi.zabbix-web dj-wasabi.zabbix-agent`

* Github / latest
* Ansible Galaxy / 1.1.0

**Ansible Version**

```
ansible 2.9.0
```

**Targetted hosts**
Concerns the following OS(es):
* Ubuntu

**Expected behavior**
It does work with 2.9.0

**Additional context**
-

Anyway, keep up the good work! :)

**Comment by dj-wasabi** [comment]
Hi @gregolsky 

Thank yoy for creating an issue. @m3t4Lm4n created a PR and is merged, so I'll close this issue.
I'll try to create a new release this weekend.

**Comment by gregolsky** [comment]
Thanks guys!
