### ISSUE TITLE
Zabbix repositories should follow the upstream

### ISSUE THREAD

**Issue by viniciusferrao** [dj-wasabi/ansible-zabbix-server#165]
**Describe the bug**
The repository file should follow what the Zabbix upstream sets up to avoid breakage. And there's a typo on the zabbix-non-supported file, since it declares itself as zabbix-supported. Using the upstream will solve the typo automatically.

Another issue is that the GPG is wrong. The upstream uses a different file: `/etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591 ` for the main repo.

**Installation method/version**
* Github / latest

**Ansible Version**

```
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Targetted hosts**
Concerns the following OS(es):
* CentOS
* Red Hat Enterprise Linux

**Expected behavior**
Use the same repositories as the upstream:

```
[root@headnode yum.repos.d]# cat zabbix.repo 
[zabbix]
name=Zabbix Official Repository - $basearch
baseurl=http://repo.zabbix.com/zabbix/4.0/rhel/7/$basearch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591

[zabbix-debuginfo]
name=Zabbix Official Repository debuginfo - $basearch
baseurl=http://repo.zabbix.com/zabbix/4.0/rhel/7/$basearch/debuginfo/
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX-A14FE591
gpgcheck=1

[zabbix-non-supported]
name=Zabbix Official Repository non-supported - $basearch
baseurl=http://repo.zabbix.com/non-supported/rhel/7/$basearch/
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
gpgcheck=1
```

**Additional context**
Nothing

**Comment by dj-wasabi** [comment]
Was fixed a while ago, therefor closing.
