### ISSUE TITLE
zabbix_repo - inconsistent use between server and agent roles.

### ISSUE THREAD

**Issue by blofeldthefish** [dj-wasabi/ansible-zabbix-server#17]
In ansible-zabbix-server, zabbix_repo is a boolean, whereas (following some adjustments for epel handling) zabbix_repo is a string.

When hooking both roles into a playbook, ansible-playbook barfs:
------------------------------------------------------------------------------------------------------------------------------
TASK: [dj-wasabi.zabbix-server | RedHat | Install basic repo file] ************ 
fatal: [xxx.xxx.xxx.xxx] => error while evaluating conditional: zabbix

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/install-zabbix-server.retry
------------------------------------------------------------------------------------------------------------------------------

I have tweaked my local installation, to get around this issue (but only for my exact use case - installing zabbix server + agent on CentOS 7)

Is there any merit in adjusting the zabbix_repo in ansible-zabbix-server to match the agent role, or is it bad practice to try and wrap both of these roles into one playbook anyway ?!!

**Comment by dj-wasabi** [comment]
Hi @blofeldthefish 

You are absolutely right. Both roles should use the same 'overall' variables like `zabbix_repo`, `zabbix_version` etc ...

**Comment by dj-wasabi** [comment]
I pushed an fix for this. I use the same method as the Zabbix Agent, this would allow to use the EPEL version when people want to.

Please let me know if you have issues with this.

**Comment by blofeldthefish** [comment]
For my particular use case, (install server + agent onto CentOS 7) works like a charm.

I sight checked non-redhat modules with prior version, so would expect those to work well too!!

Not sure of how Ansible Galaxy and Github interact, but an install via ansible-galaxy still installs versions 0.5.1 (not the 0.6.0 codebase)

Appreciate the turnaround on this one...

**Comment by dj-wasabi** [comment]
Hi @blofeldthefish 

Thank you. I still have some things that I want in the 0.6.0 release so it isn't available on the galaxy yet.

**Comment by dj-wasabi** [comment]
Just pushed 0.6.0 to the galaxy.
