### ISSUE TITLE
Make it optional to start Zabbix-server

### ISSUE THREAD

**Issue by pugnacity** [dj-wasabi/ansible-zabbix-server#173]
**Is your feature request related to a problem? Please describe.**
We're running Zabbix in HA mode which means the Zabbix server will be started by Keepalived

**Describe the solution you'd like**
make it optional to disable the service.

**Comment by tenhishadow** [comment]
related PR: https://github.com/dj-wasabi/ansible-zabbix-server/pull/174

**Comment by dj-wasabi** [comment]
Merged the PR. 👍
