### ISSUE TITLE
what to file the highlighted commands after the script runs at once

### ISSUE THREAD

**Issue by Rajulolabhattu** [dj-wasabi/ansible-zabbix-server#178]
![Screenshot (77)](https://user-images.githubusercontent.com/62057171/79255588-23e26f80-7ea4-11ea-844e-e8114e6380ee.png)

**Comment by dj-wasabi** [comment]
Hi @Rajulolabhattu 

I don't see what this has to do with the Ansible Role. So I'll close this issue.

Kind regards,
Werner
