### ISSUE TITLE
server_dbhost allows for remote database but role does not fully support setting up on remote db

### ISSUE THREAD

**Issue by srvg** [dj-wasabi/ansible-zabbix-server#2]
The server_dbhost var defaults to localhost, and seems to possibly be used to set up the database on a separate host.

The db specific tasks however, do no all use this parameter, especially the database and user creation tasks.

**Comment by lhoss** [comment]
We had the same issue  (db-server on a different host than the zabbix-master) and I got a simple fix for this, that I will push tomorrow in a PR :+1:

**Comment by lhoss** [comment]
@srvg can you check if my fix also works for you?
Thanks!

**Comment by srvg** [comment]
Left a comment at #11
