### ISSUE TITLE
unknown parameter "HistoryTextCacheSize" in config file

### ISSUE THREAD

**Issue by ad-lebedev** [dj-wasabi/ansible-zabbix-server#26]
Hi!
Condition in [this line](https://github.com/dj-wasabi/ansible-zabbix-server/blob/master/templates/zabbix_server.conf.j2#L273) of zabbix_server.conf.j2 template seems wrong for 3.2 installation.
May be it's better to change all hardcoded `3.0` related conditions to `>=3.0` and `<3.0`?

**Comment by dj-wasabi** [comment]
Hi. Yes, I think you are right.

**Comment by rfults** [comment]
Verified when commenting out this item in the template I was able to complete the installation successfully.

**Comment by dj-wasabi** [comment]
Old issue and is already fixed a while back, so will close it.
