### ISSUE TITLE
datafiles_path for Zabbix 3.2.1 wrong on RedHat 

### ISSUE THREAD

**Issue by mjuenema** [dj-wasabi/ansible-zabbix-server#28]
The logic in `tasks/RedHat.yml` sets the `datafiles_path` wrongly to `/usr/share/doc/zabbix-server-{{ database_type }}-{{ zabbix_version }}*/create` for Zabbix 3.2.1 (3.2.\* ?). 

The correct path should be`"/usr/share/doc/zabbix-server-{{ database_type }}-{{ zabbix_version }}*` as for Zabbix 3.0.

**Comment by cody-young** [comment]
I get a similar issue on Ubuntu 14 installing zabbix-server-3.2: can't cd to /usr/share/zabbix-server-mysql

**Comment by cody-young** [comment]
I tried with a symlink and it's complaining that images.sql.gz doesn't exist. Looking in the folder I see a create.sql.gz. Maybe the file name changed as well?

**Comment by rfults** [comment]
Similar issue found here on RHEL 7.2.  After correcting the path I was able to move forward, however install fails at TASK[dj-wasabi.zabbix-server : PostgreSQL | Importing \\ schema file] as the only file listed in the path is create.sql.gz.  Seems that the .sql files are not available when you are installing from a package vs source:  https://www.zabbix.com/documentation/3.2/manual/appendix/install/db_scripts.

**Comment by rfults** [comment]
Added ignore_errors: true to the last 3 tasks in  tasks/postgresql.yml in order to move forward.

**Comment by dj-wasabi** [comment]
Which version of the role are you using?

**Comment by dj-wasabi** [comment]
Closing non-responsive and outdated issue. If it is still an issue, please provide some details.
