### ISSUE TITLE
dj-wasabi.zabbix-server : PostgreSQL | Create database permissions error

### ISSUE THREAD

**Issue by rfults** [dj-wasabi/ansible-zabbix-server#29]
I am receiving the following error when trying to install 3.2 on RHEL 7.2 with PostgreSQL at TASK [dj-wasabi.zabbix-server : PostgreSQL | Create database]:

fatal: [usor7dzabx01]: FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}.

I've tried modifying the task in the playbook to resolve with no luck.  Running as a sudoer.

**Comment by dj-wasabi** [comment]
Hi @rfults 

Can the user sudo to the `postgres` user on the system where you want to install Zabbix Server? Is PostgreSQL installed on this host, or is it running on a different host?

**Comment by rfults** [comment]
PostgreSQL was installed on the same box as the Zabbix Server and I was able to sudo to the postgres user account.  I attempted to move over to the MySQL install after hitting this error and not being able to resolve it within a few minutes.

**Comment by rfults** [comment]
Seems something went wrong with the installation of PostgreSQL.  After rebuilding the box and installing postgresql-9.3 with a playbook I was able to move past this error.
