### ISSUE TITLE
dj-wasabi.zabbix-server : MySQL | Create database exception: cannot connect

### ISSUE THREAD

**Issue by rfults** [dj-wasabi/ansible-zabbix-server#30]
Receiving the following error when trying to install 3.2 on RHEL 7.2 with MySQL at TASK [dj-wasabi.zabbix-server : MySQL | Create database]:

fatal: [usor7dzabx01 -> usor7dzabx01]: FAILED! => {"changed": false, "failed": true, "msg": "unable to find /root/.my.cnf. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"}

**Comment by dj-wasabi** [comment]
Hi @rfults 

Is the Zabbix Server running on the same server as MySQL?
Do you have a `/root/.my.cnf` on the system where you want to install Zabbix Server?

**Comment by rfults** [comment]
MySQL and Zabbix were on the same server.  I suspect there may have been installation issues with MySQL as RedHat has migrated to MariaDB now and that may have changed some file locations.  I am rebuilding my test VM now (as I didn't snapshot it first) and will follow up with any other findings.
