### ISSUE TITLE
Random other issues with configuration on RHEL 7.2

### ISSUE THREAD

**Issue by rfults** [dj-wasabi/ansible-zabbix-server#31]
After completing the playbook run successfully I had to resolve several other issues with the Zabbix 3.2.1 install using PostgreSQL on RHEL 7.2:

- I had to drop the database and recreate it as zabbix, then change the ownership to zabbix-server in PostgreSQL.  Zabbix-server was throwing an error that it was not a Zabbix database otherwise.  Had to blank DBHost in zabbix.conf and change DBName.  Required reboot for all changes to be noticed.

- Had to install zabbix-java-gateway to make web interface work and updated httpd configs to look for zabbix on port 8080 as there are pre-configured vhosts using port 80 with the dependent apache playbook.

- SELINUX is a problem as usual, either disable it or add a policy for zabbix using "setsebool -P zabbix_can_network 1".

Hope this info is helpful in your updates.

**Comment by dj-wasabi** [comment]
A lot of changes are applied since this issue was created. Can you please tell me which of them still applies?

**Comment by dj-wasabi** [comment]
Closing non-responsive and outdated issue. If it is still an issue, please provide some details.
