### ISSUE TITLE
Ubuntu 16.04 - unable to install - wrong PHP dependency

### ISSUE THREAD

**Issue by nysander** [dj-wasabi/ansible-zabbix-server#43]
TASK [dj-wasabi.zabbix-server : Debian | Install php5-mysql] *******************
    fatal: [192.168.0.171]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'php5-mysql' is available"}

On Ubuntu 16.04 there is only php7.0-mysql package, you should probably depend on php-mysql virtual package

**Comment by frennkie** [comment]
Can confirm this. 
It works when I change to `pkg=php-{{ database_type }}`. But that package is not available on older Ubuntu versions. So I assume a `when` condition is needed.

**Comment by dj-wasabi** [comment]
Hi @nysander @frennkie 

Yes, I tested yesterday on Debian 8 that php-mysql don't exists. So a `when` is probably the best case for this, unless there are more packages that are different and then we would be able to include var file for specific os'es.

**Comment by frennkie** [comment]
There are more packages that are specific to installing on Ubuntu 16.x due to PHP7 being the default.. I did a successful install yesterday and can post the list of php7.0-.. things I installed later.

**Comment by frennkie** [comment]
I installed these (on Ubuntu 16.04):

- libapache2-mod-php7.0
- php7.0-bcmath 
- php7.0-mbstring 
- php7.0-ldap 
- php7.0-mysql 
- php7.0-xml

**Comment by dj-wasabi** [comment]
Hi @frennkie 

Thanks!
I'll try to think of a way to properly implement this.

**Comment by dj-wasabi** [comment]
I merged a PR which fixes this issue.

**Comment by stephankn** [comment]
The commit only fixes it for exactly 16.04. Better test for greater-same on the version.

See my comment: https://github.com/dj-wasabi/ansible-zabbix-server/commit/1251c6c4c2f9357b589b21b1dcd08b9645deae41#commitcomment-20949317
