### ISSUE TITLE
Invalid ServerAlias is added to Apache VirtualHost

### ISSUE THREAD

**Issue by stephankn** [dj-wasabi/ansible-zabbix-server#45]
An invalid (maybe even harmful) ServerAlias is added:

```ServerAlias 2.4```

this was introduced here:

https://github.com/dj-wasabi/ansible-zabbix-server/blob/d17069c15ee50aad292c27e470e4fac1544cc68f/templates/apache_vhost.conf.j2#L3

I believe this is useless at this location. Why should my host be called "2.4"? 

My suggestion is to completely remove this line.

**Comment by dj-wasabi** [comment]
Hi @stephankn 

I've removed the line. It was indeed not needed.
