### ISSUE TITLE
PostgreSQL questions

### ISSUE THREAD

**Issue by Veske** [dj-wasabi/ansible-zabbix-server#51]
Does this role assume that Postgresql user and group are created before hand or it assumes that postgresql installation creates them? Because on Centos 7 it seems that postgresql does not do these things.

Also it seems that PostgreSQL will not even come up with this role. Postgresql-server and postgresql-contrib are not installed so the service is not even existing. Does the role assume that the server is also pre installed already?

**Comment by dj-wasabi** [comment]
Hi,

This role assumes that PostGreSQL is correctly installed. It doesn't matter if this is done manually or via an other role. The only postgresql things that this role does are specific to correct working of Zabbix. This includes creation of the zabbix database and filling the database with basic zabbix data.
