### ISSUE TITLE
Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")" 

### ISSUE THREAD

**Issue by J0hnson** [dj-wasabi/ansible-zabbix-server#52]
When i tried to install zabbix server 3.2 in centos7.3 ,the mysql database cannot be created.

The error message is:
 
TASK [dj-wasabi.zabbix-server : MySQL | Create database] ***********************
fatal: [zabbix.paastest.cn -> zabbix.paastest.cn]: FAILED! => {"changed": false, "failed": true, "msg": "unable to find /root/.my.cnf. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"}
        to retry, use: --limit @/etc/ansible/roles/main.retry

The DB has been installed in the host:
Package 1:mariadb-5.5.52-1.el7.x86_64 already installed and latest version

**Comment by 4c74356b41** [comment]
Same error on Ubuntu 16.04 LTS and mysql

```
fatal: [master -> None]: FAILED! => {"changed": false, "failed": true, "msg": "unable to find /root/.my.cnf. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\")"}
```

**Comment by dj-wasabi** [comment]
Which Ansible role do you use for installing MySQL|MariaDB?

**Comment by 4c74356b41** [comment]
I'm using mysql. the default that comes with your playbook

**Comment by 4c74356b41** [comment]
@dj-wasabi any ideas?

**Comment by dj-wasabi** [comment]
This role will only install Zabbix Server and depending on a property, MySQL or PostGreSQL is used and a database is configured and data is installed. You'll have to find a suitable Role for installing the database, in this case mysql. The geerlingguy.mysql is a very good one.

**Comment by 4c74356b41** [comment]
oh so, I though its contained in it, so I just have to install that from ansible-galaxy and it will work? or do I have to add something? @dj-wasabi

**Comment by 4c74356b41** [comment]
I can confirm that this work, sorry, I thought that this is handled internally by your role.

**Comment by irparaja** [comment]
Iam getting error to create database while ansible playbook


PLAY [database] ***************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************
ok: [192.168.56.4]

TASK [mysql : install mysql] **************************************************************************************************************
ok: [192.168.56.4]

TASK [mysql : install Mysql-python install] ***********************************************************************************************
ok: [192.168.56.4]

TASK [mysql : create database] ************************************************************************************************************
fatal: [192.168.56.4]: FAILED! => {"changed": false, "msg": "unable to find /root/.my.cnf. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"}
 [WARNING]: Could not create retry file '/etc/ansible/site.retry'.         [Errno 13] Permission denied: u'/etc/ansible/site.retry'
PLAY RECAP ********************************************************************************************************************************
192.168.56.4               : ok=3    changed=0    unreachable=0    failed=1

**Comment by dj-wasabi** [comment]
Hi @irparaja 
Do you already have a MySQL service running on the host?

**Comment by irparaja** [comment]
Hi,

i have a small doubt here that is i am running five docker containers with ubuntu kernel, if the ubuntu kernel is went something wrong then what about the five docker container, at the time containers going down or still running.
