### ISSUE TITLE
Wrong directory api instead of app in apache_vhost.conf.j2

### ISSUE THREAD

**Issue by sh0thub** [dj-wasabi/ansible-zabbix-server#53]
Hello, I found little typo in template apache_vhost.conf.j2 on line 10:

{% set directory_paths = ['/usr/share/zabbix/conf', '/usr/share/zabbix/api', '/usr/share/zabbix/include', '/usr/share/zabbix/include/classes'] %}

Instead of '/usr/share/zabbix/api' there should be correct path '/usr/share/zabbix/app'

Thanks for great playbook

**Comment by dj-wasabi** [comment]
Pushed a fix for this: Fixing issue #53 renaming api to app #58
Is soon available as release 0.8.0
