### ISSUE TITLE
Extract zabbix-web component from role ?

### ISSUE THREAD

**Issue by flyapen** [dj-wasabi/ansible-zabbix-server#55]
At the moment it's possible to skip installation of the zabbix-web component, but there are other steps in the tasks that perform tasks related to zabbix-web regardless of it's installation ( such as installing php packages etc. ). 

Since all other zabbix components are extracted to their separate role ( proxy, javagateway, agent ) wouldn't it make sense to move all zabbix-web related steps to its own ansible role? I would be happy to help with this effort. 

As an alternative, would you welcome a pull request that disables all zabbix-web related steps based on the variable to select zabbix-web installation?

**Comment by dj-wasabi** [comment]
Hi @flyapen 

Yes, it totally makes sense to make a separate role for everything related to zabbix-web and remove it from this Zabbix Server role. Will take a look at it. At least all api related tasks and the ones you already mention like the php stuff needs to be placed there.

👍

**Comment by flyapen** [comment]
Great, we'll be glad to contribute to the new role when it's available. In the meanwhile I've created a pull requested to skip the zabbix-web related tasks so a clean install for zabbix-server is possible.

**Comment by dj-wasabi** [comment]
@flyapen 

Currently busy with a `1.0.0` release for all my Zabbix roles and then Zabbix Web is completely seperated from the Zabbix Server. Already have a role https://github.com/dj-wasabi/ansible-zabbix-web, but will work better when the Zabbix Server is updated.

**Comment by dj-wasabi** [comment]
I just released 1.0.0 for the Zabbix Server, Web and Agent that includes the split of the Web stuff into their own role.
