### ISSUE TITLE
consider releasing a new version as 0.7 is quite old

### ISSUE THREAD

**Issue by stephankn** [dj-wasabi/ansible-zabbix-server#57]
Would be great to see a newer version than 0.7 tagged, maybe even as release.

There had been quite a few fixes since last December. How about making them officially available?

At least I feel better syncing to a more officially approved release than just to a commit hash.

**Comment by dj-wasabi** [comment]
Yes, you are right. Will create a 0.8.0 release today or tomorrow.

**Comment by dj-wasabi** [comment]
I just pushed release 0.8.0 to the galaxy.
