### ISSUE TITLE
systemd service zabbix-server not enabled on Ubuntu 16.04

### ISSUE THREAD

**Issue by stephankn** [dj-wasabi/ansible-zabbix-server#60]
I did a clean install on a 16.04.2 LTS (Xenial Xerus) test machine.
after installation the Zabbix server is running (confirmed by systemctl and web interface).

```
$ sudo systemctl status zabbix-server
● zabbix-server.service - Zabbix Server
   Loaded: loaded (/lib/systemd/system/zabbix-server.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-06-16 19:43:47 UTC; 28s ago
  Process: 9507 ExecStart=/usr/sbin/zabbix_server -c $CONFFILE (code=exited, status=0/SUCCESS)

```
Unfortunately this already shows that the service is started, but not enabled. So after the next reboot it will not run.

My ansible install is on latest. I saw some reports about conflicts between systemd and sysV init scripts confusing ansible, but thought these are fixed in https://github.com/ansible/ansible-modules-core/issues/3764

```
 $ ansible --version
ansible 2.4.0 (devel 5f23aa69c6) last updated 2017/06/16 19:27:24 (GMT +000)
  config file = /home/vagrant/playbook/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/ansible/lib/ansible
  executable location = /home/vagrant/ansible/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

```

This seems to be an ansible issue but due to this issue it won't properly bring up a new installation.
I have commented about this on https://github.com/ansible/ansible/issues/22303

It can be fixed by manually enabling the service, but this defeats a bit the purpose auf automation by ansible.
`systemctl enable zabbix-server.service`

Even in case ansible gets fixed eventually in the future, this does not help for existing installs. How about adding a workaround to the handler as suggested in the ansible bugtracker?

`service: name=zabbix-server state=restarted enabled=yes use=service`

As the handler is not triggered without a change, it will not repair existing setups by running the playbook again.

Having another task (not a handler) requesting the service being started at the end might solve this.
`service: name=zabbix-server state=started enabled=yes use=service`

**Comment by dj-wasabi** [comment]
I've merged a PR, can you please take a look and validate if this works for you?

**Comment by stephankn** [comment]
I can confirm, that with the merged PR after running the role the zabbix server is now enabled and running.

```
● zabbix-server.service - Zabbix Server
   Loaded: loaded (/lib/systemd/system/zabbix-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-06-25 18:50:43 UTC; 1min 59s ago
```

Thanks for working around this specific issue.
