### ISSUE TITLE
Zabbix Server Install -- Fails with MySQL

### ISSUE THREAD

**Issue by fxfitz** [dj-wasabi/ansible-zabbix-server#63]
I'm trying to use this role to setup and configure a Zabbix Server on CentOS 7, however I can't get it to pass the MySQL part.  Am I doing something wrong?

```
TASK [dj-wasabi.zabbix-server : MySQL | Create database] *******************************
fatal: [vagrant-cms-zabbix.cyclops -> 192.168.200.11]: FAILED! => {"changed": false, "failed": true, "msg": "unable to find /root/.my.cnf. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"}
```

Relevant configuration:
```
zabbix_version: 3.2
zabbix_repo: zabbix
zabbix_agent_package_state: latest
zabbix_selinux: true
zabbix_timezone: UTC
zabbix_web: true
zabbix_database_creation: true
zabbix_database_sqlload: true
database_type: mysql
database_type_long: mysql
server_dbport: 3306
```

**Comment by dj-wasabi** [comment]
I think you don't use a mysql role? This Zabbix role will only install Zabbix, not MySQL.

**Comment by fxfitz** [comment]
Actually, this is what we had to do: https://github.com/CTL-Fed-Security/ansible-zabbix-server/commit/ad83b5db89f973ae4a671bada0ab086b2d687618

Sorry, I've been meaning to contribute some of that upstream, but I was under the gun for some quick fixes.

**Comment by dj-wasabi** [comment]
Ok, but that is not really the responsibility of the (this) Zabbix role, but for the mariadb/mysql role you are using. This role assumes that Apache/MariaDB or any other dependent role is executed successfully.

**Comment by fxfitz** [comment]
Yup, I see what you're saying: you're totally right. It's definitely the job of the mariadb/mysql role.

So, to use this role [with a mariadb backend], the idea is to:

1. use a separate mariadb role to get the database running
2. run this role and have the zabbix-server communicate with maria db

Would it make sense for this role to have the option of automatically configuring the database? I ask because I typically think of roles as when I run them, once they're done, the service (in this case Zabbix-Server) is completely good to go.

But I could be thinking about it wrong too. Would love to hear your thoughts. :-)

**Comment by dj-wasabi** [comment]
Sorry for late answer. What do you mean with `automatically configuring the database?`?

This role already creates a `zabbix-server` database in MySQL and imports the sql files to create the basic table structure Zabbix needs. If there are more "actions" needed to configure the created MySQL database for the Zabbix Server, then yes please add them if you think this is needed for a default installation/configuration.
