### ISSUE TITLE
Release 1.0.0 - Issue/Task List

### ISSUE THREAD

**Issue by fxfitz** [dj-wasabi/ansible-zabbix-server#70]
@dj-wasabi: I'd like to help as much as I can speed along the release of 1.0.0 for all of your Zabbix roles (we're using them extensively at this point).

What would you think about defining some issues/tasks that you'd like to see done in order to get 1.0.0 out the door so I can start contributing?

Thanks!

**Comment by dj-wasabi** [comment]
Hi @fxfitz 

Thank you for the offer.
This Tuesday or Wednesday, I want to release the 1.0.0 for the Agent, Server and the Web. I stopped hoping for the merge of 2 PR's that I created at Ansible that fixes 2 issues on the Agent.

The Proxy and the Java Gateway will follow later. Most important thing for me is from ini to yml, use Zabbix 3.4 as default and make sure the tests are working/up2date (With Molecule).

**Comment by dj-wasabi** [comment]
It will be a few days later. Molecule V2 has been released and this would be a good time to use this with the 1.0.0 release.

**Comment by fxfitz** [comment]
Sounds good. We're holding off until pushing Zabbix stuff out to production until we can pin to 1.0.0. :-)

**Comment by dj-wasabi** [comment]
Hi @fxfitz 

Molecule V2 will be in a later release, some things is not there yet or not documented. Zabbix Web, Agent and Server is released with 1.0.0.
