### ISSUE TITLE
seperation between mysql and postgress

### ISSUE THREAD

**Issue by tshtilman** [dj-wasabi/ansible-zabbix-server#81]
Hello
even when we create a mysql database both PostgreSQL and MySQL   dependencies are require
`name: "RedHat | Install Ansible module dependencies"
yum: name=python-psycopg2
state=present
when: zabbix_database_creation
tags:
zabbix-server`

need to be separated mysql/postgress

**Comment by dj-wasabi** [comment]
Will close this issue as you already provided the pr #82
