### ISSUE TITLE
Host autoregistered in zabbix  with IP 0.0.0.0 when ListenIP sets to 0.0.0.0

### ISSUE THREAD

**Issue by andreyhammer** [dj-wasabi/ansible-zabbix-server#84]
I'm use autoregistartion in zabbix. If agent have ListenIP 0.0.0.0  , host in zabbix also have 0.0.0.0, so zabbix server cant connect to agent.  Need to comment ListenIP  in agent conf to fix it. How I can do it from playbook?

**Comment by andreyhammer** [comment]
Need to fix zabbix_agentd.conf.j2:
```
{% if zabbix_agent_listenip  !='0.0.0.0' %}
ListenIP={{ zabbix_agent_listenip }}
{% endif %}

```

**Comment by dj-wasabi** [comment]
I proved a fix in the zabbix-agent role.
