### ISSUE TITLE
Zabbix 4

### ISSUE THREAD

**Issue by rgarrigue** [dj-wasabi/ansible-zabbix-server#93]
All's the title, I see this is good to go up to Zabbix 3.4. Can you add version 4 ?

**Comment by dj-wasabi** [comment]
Zabbix 4 will be added once Zabbix 4 is released.

**Comment by ericsysmin** [comment]
@dj-wasabi 4 is added, no commit yet for it tho

**Comment by dj-wasabi** [comment]
@ericsysmin yeah there is.. 😄
