### ISSUE TITLE
unable to connect to database

### ISSUE THREAD

**Issue by esxi1979** [dj-wasabi/ansible-zabbix-server#94]
Hello 

I got below err 

fatal: [xx -> xxx]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"}

i am using 
ansible 2.4.2.0

Destination host is RHEL 7

pls suggest thx

**Comment by dj-wasabi** [comment]
Hi,

Is MySQL running? Have you set the properties mentioned in the readme in the database paragraph?

Kind regards,
Werner

**Comment by davidbonnici1984** [comment]
The issue might be  related to SELinux... try 
Check if "sudo getenforce" is enforcing or permissive. If it is enforcing.
Try with "sudo setenforce 0" and check if it connects with the database.
