### ISSUE TITLE
installation does not create database on remote host

### ISSUE THREAD

**Issue by oskapt** [dj-wasabi/ansible-zabbix-server#96]
**Describe the bug**

If using a remote db host, the role sets `delegated_db_host` and uses this later to install `create.sql.gz`. The problem is that `create.sql.gz` exists on the Zabbix host, not on the remote db host.

```
TASK [zabbix-server : MySQL | Create database and import file >= 3.0] ***********************************************************************
fatal: [zabbix -> support.scl01.filon.tech]: FAILED! => {"changed": false, "msg": "target /usr/share/doc/zabbix-server-mysql/create.sql.gz does not exist on the host"}
```

**Installation method/version**

* Github / latest

**Ansible Version**

```
ansible 2.5.2
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/ansible/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/ansible/venv/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu

**Expected behavior**

The database should have been installed.

**Additional context**

I'm working on a resolution and will submit a PR if it works.

**Comment by dj-wasabi** [comment]
Outdated. If this still is an issue, please open a new PR in the repository on  https://github.com/ansible-collections/community.zabbix/
